#define TK_ASSIGNOP 1
#define TK_COMMENT 2
#define TK_FIELDID 3
#define TK_ID 4
#define TK_NUM 5
#define TK_RNUM 6
#define TK_ERROR 7
#define TK_FUNID 8
#define TK_RUID 9
#define TK_WITH 10
#define TK_PARAMETERS 11
#define TK_END 12
#define TK_WHILE 13
#define TK_UNION 14
#define TK_ENDUNION 15
#define TK_DEFINETYPE 16
#define TK_AS 17
#define TK_TYPE 18
#define TK_MAIN 19
#define TK_GLOBAL 20
#define TK_PARAMETER 21
#define TK_LIST 22
#define TK_SQL 23
#define TK_SQR 24
#define TK_INPUT 25
#define TK_OUTPUT 26
#define TK_INT 27
#define TK_REAL 28
#define TK_COMMA 29
#define TK_SEM 30
#define TK_COLON 31
#define TK_DOT 32
#define TK_ENDWHILE 33
#define TK_OP 34
#define TK_CL 35
#define TK_IF 36
#define TK_THEN 37
#define TK_ENDIF 38
#define TK_READ 39
#define TK_WRITE 40
#define TK_RETURN 41
#define TK_PLUS 42
#define TK_MINUS 43
#define TK_MUL 44
#define TK_DIV 45
#define TK_CALL 46
#define TK_RECORD 47
#define TK_ENDRECORD 48
#define TK_ELSE 49
#define TK_AND 50
#define TK_OR 51
#define TK_NOT 52
#define TK_LT 53
#define TK_LE 54
#define TK_EQ 55
#define TK_GT 56
#define TK_GE 57
#define TK_NE 58